CREATE DATABASE Ejercicio2;
USE Ejercicio2;

CREATE TABLE TRATAMIENTOS(
TraNumero INT(14) PRIMARY KEY,
TraFechaAsignado DATE NOT NULL,
TraDescripcion VARCHAR (200),
TraFechaInicio DATE NOT NULL,
TraFechaFin DATE NOT NULL,
TraObservaciones VARCHAR(100),
TraPaciente INT (10) NOT NULL,
CitObservaciones VARCHAR (100)
);

CREATE TABLE PACIENTES(
PacIdentificacion INT(10) PRIMARY KEY,
PacNombres VARCHAR (40) NOT NULL,
PacApellidos VARCHAR (40) NOT NULL,
PacFechaNacimiento DATE NOT NULL,
Pacsexo VARCHAR (10) NOT NULL
);

CREATE TABLE CITAS(
CitNumero INT(14) PRIMARY KEY,
CitFecha DATE NOT NULL,
CitHora TIME NOT NULL,
CitPaciente INT (10) NOT NULL,
CitMedico INT (10) NOT NULL,
CitConsultorio INT(4) NOT NULL,
CitEstado VARCHAR (10) NOT NULL,
CitObservaciones VARCHAR (100)
);


CREATE TABLE MEDICOS(
MedIdentificacion INT(10) PRIMARY KEY ,
MedNombres VARCHAR (40) NOT NULL,
MedApellidos VARCHAR (40) NOT NULL
);

CREATE TABLE CONSULTORIOS(
ConNumero INT(4) PRIMARY KEY,
ConNombre VARCHAR (20) NOT NULL
);

ALTER TABLE CITAS ADD CONSTRAINT fk_CitaMedico FOREIGN KEY (CitMedico) 
REFERENCES MEDICOS (MedIdentificacion) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CITAS ADD CONSTRAINT fk_CitaConsultorio FOREIGN KEY (CitConsultorio) 
REFERENCES CONSULTORIOS (ConNumero) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CITAS ADD CONSTRAINT fk_CitaPaciente FOREIGN KEY (CitPaciente) 
REFERENCES PACIENTES (PacIdentificacion) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TRATAMIENTOS ADD CONSTRAINT fk_TratamientoPaciente FOREIGN KEY (TraPaciente) 
REFERENCES PACIENTES (PacIdentificacion) ON DELETE CASCADE ON UPDATE CASCADE;
